name: Build Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel python3-venv libffi-dev libssl-dev libsqlite3-dev zlib1g-dev

      - name: Build APK with Buildozer (Docker)
        run: |
          pip install buildozer
          cd src3/app
          echo "Zawartość katalogu src3/app przed buildem:"
          ls -l
          echo "Zawartość buildozer.spec:"
          cat buildozer.spec || echo "Brak pliku buildozer.spec!"
          buildozer android clean || true
          n=0
          until [ "$n" -ge 5 ]
          do
            echo "Próba $((n+1)) z 5"
            buildozer android debug --verbose && break
            n=$((n+1))
            echo "Build failed, retrying in 30 seconds... ($n/5)"
            echo "Zawartość .buildozer/android/ po nieudanej próbie:"
            ls -l .buildozer/android/ || true
            echo "Zawartość .buildozer/android/platform/ po nieudanej próbie:"
            ls -l .buildozer/android/platform/ || true
            sleep 30
          done

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: fitogar-debug-apk
          path: /bin/*.apk

